### ISSUE TITLE
Default Steam schema language to English

### ISSUE THREAD

**Issue by msolefonte** [achievement-watcher/celes#12]
In the version v1, Steam schema data was obtained by invoking a function similar to the one following:

```typescript
async getGameData(appId: string, lang: string, key?: string | undefined): Promise<IGameData> {
    if (!this.steamLanguages.includes(lang)) {
        throw 'Language selected not supported by Steam API';
    }

    ...
}
```

As can be seen, right now an error is thrown if the language selected is not available at Steam. I think it would be more practical to default that language to English, being the more universal one. Any thoughts @xan105?

**Comment by xan105** [comment]
Yes, we can fallback to English as default.
That's what the Steam Web API does.

**Comment by msolefonte** [comment]
Fixed.
