### ISSUE TITLE
The achievement location files should not be universal but defined by the plugin

### ISSUE THREAD

**Issue by msolefonte** [achievement-watcher/celes#13]
Right now, the function `getAchievementListFromGameFolder` at `SteamUtils` uses a defined constant `achievementLocationFiles` as the list of folders that should be checking for achievements. This list is not universal and should be adapted to each plugin.

```typescript
static async getAchievementListFromGameFolder(gameFolder: string) {
        const achievementLocationFiles: string[] = [
            'achievements.ini',
            'achievements.json',
            'achiev.ini',
            'stats.ini',
            'Achievements.Bin',
            'achieve.dat',
            'Achievements.ini',
            'stats/achievements.ini',
            'stats.bin',
            'stats/CreamAPI.Achievements.cfg'
        ];
        
        ...
}
```

---

Knowledge, so far:

- **ALI213:** `Achievements.Bin`
- **Codex:** `achievements.ini`
- **CreamAPI:** `stats/CreamAPI.Achievements.cfg`
- **Goldberg:** `achievements.json`
- **Reloaded:** `stats/achievements.ini`
- **SmartSteamEmu:** `stats.bin`

**Comment by xan105** [comment]
I will update the list. I have to look in my code for some.

**Comment by msolefonte** [comment]
Some changes have been added in #23 to allow this kind of split but I need a proper list to continue. Check it when you can @xan105.

**Comment by msolefonte** [comment]
Added at #39. Some may need to be reviewed.
