### ISSUE TITLE
Patch ini parsing

### ISSUE THREAD

**Issue by xan105** [achievement-watcher/celes#18]
Reminder to use the module `ini` with this [patch](https://github.com/achievement-watcher/achievement-watcher/blob/master/app/patches/ini%2B1.3.5.patch) to avoid a problematic case where if a achievement's apiname contains a `.` it would interfere in the ini to js object conversion of said module as a `.` is used to separate object properties.

Recommended to use the module `patch-package` as dev dep. to automatize patching when using npm i
```
"dependencies": {
    "ini": "^1.3.5"
},
 "devDependencies": {
    "patch-package": "^6.2.1"
}
```
<hr>

> Fix bug where a "." in ini file section for ach name would fail because the ini parser would split it into nested object

cf: achievement-watcher/achievement-watcher@1f26aa2a0e42632f6e946cedc780dfbe77c359c8

**Comment by msolefonte** [comment]
I am actually not comfortable with this. Nor patching packages nor using packages that need to be patched. How is it possible that a package like `ini`, by `npm`, holds this kind of problem? Aren't there alternatives?

**Comment by xan105** [comment]
This is the discussion of the problem : https://github.com/npm/ini/issues/60
There are more than one pr to solve it. But they aren't merged.
Not the first time I had to use patch-package for this kind of case where I need a pr merged, etc

I do not have experience with other npm package for ini parsing (if there is any).

**Comment by msolefonte** [comment]
To check:

* https://www.npmjs.com/package/js-ini
* https://www.npmjs.com/package/properties
* https://www.npmjs.com/package/any-json
* https://www.npmjs.com/package/iniparser

**Comment by msolefonte** [comment]
Added at #39. I tried multiple libraries and `js-ini` is the lighter one that works.

**Comment by xan105** [comment]
I confirm that js-ini doesn't go boom with a dot.

```ini
[achievement.goes.boom01]
timestamp = 0
```

```js
"use strict"

const oldini = require("ini");
const ini = require("js-ini");
const fs = require('fs');

const raw = fs.readFileSync('test.ini', 'utf8');

console.log(ini.parse(raw));
console.log(oldini.parse(raw));
```

```js
{
  'achievement.goes.boom01': { timestamp: 0 }
}
{
  achievement: { goes: { boom01: [Object] } }
}
```

**Comment by msolefonte** [comment]
I actually added these tests:

Pull
        ...
        √ All active achievement names are in the schemas
        √ All active achievement unlock times are valid
        √ All active achievement progress values are valid
        ...

This issue is now automatically tested with the first test. If the achievement name is not in the schema, it throws a very specific error notifying the conflicting platform, source, appid and achievement name.
