### ISSUE TITLE
Address concurrency issues

### ISSUE THREAD

**Issue by msolefonte** [achievement-watcher/celes#22]
Issues related to concurrency have to be resolved before reaching production. The most possible example of this is the following:

1. Showcase starts, function `pull()` is called.
1. Watchdog detects a game closing and calls `addGamePlaytime()`.
1. `pull()` scraps the local files.
1. `addGamePlaytime()` loads local database status.
1. `pull()` loads local database status.
1. `addGamePlaytime()` generates new game data including the new playtime. 
1. `pull()` generates new game data based on the merge of the scrap and the load.
1. `addGamePlaytime()` updates the database with the new game data.
1. `pull()` updates the database with the new game data.
1. Playtime goes boom.

This kind of issue is very specific and rare and, based on the current architecture, only affects the watchdog. However, it would be very interesting to address it before it becomes a major problem / to prevent random issues.

**Comment by xan105** [comment]
Could this be avoided if playtime was stored separately ? or it wouldn't change a thing

**Comment by msolefonte** [comment]
> Could this be avoided if playtime was stored separately ? or it wouldn't change a thing

Playtime is not the only problem. Also happens with achievements unlock time and basically with any situation where two components can update the database at the same time. Showcase and Watchdog in this case, but maybe also other components in the future.

Do not worry about it though, I am quite used to work with this kind of issues.

**Comment by msolefonte** [comment]
Fixed at https://github.com/achievement-watcher/celes/pull/23.
