### ISSUE TITLE
Add a plugin for GreenLumaReborn

### ISSUE THREAD

**Issue by msolefonte** [achievement-watcher/celes#35]

**Comment by msolefonte** [comment]
@xan105 Are these games achievements related to the Registries? Really? Who thought it was a good idea?

**Comment by xan105** [comment]
The author of these tools usually store data to the Windows registry.
cf: GreenLuma Reborn, GreenLuma2020, LumaPlay
I have no opinion on the matter it's another medium I guess.
Probably a bitch for test automation tho ^^

**Comment by msolefonte** [comment]
GreenLuma Reborn and GreenLuma2020 is more or less the same, isn't it?

**Comment by xan105** [comment]
GreenLuma2020 is the continuation of the now deprecated GreenLuma Reborn. Achievement wise data is stored similarly

**Comment by msolefonte** [comment]
Fixed at #47
