### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by msolefonte** [achievement-watcher/celes#9]
Each plugin should have its own test, including as much variability as possible.

**Comment by xan105** [comment]
I will gather as much sample as I can

**Comment by msolefonte** [comment]
Any update with the samples?

**Comment by msolefonte** [comment]
By the way, I have been thinking about testing and I think I may use `mocha` and `chai`. Any preference?

**Comment by xan105** [comment]
I'm not familiar with these tools 🙃 I will let you be the judge.

> Any update with the samples?

In progress :)

**Comment by msolefonte** [comment]
I added 80% coverage with as per the PR #37. By now, plugin coverage only includes Codex and Reloaded as I have not a lot of samples. I also want to add tests to introduce obvious errors, like invalid achievement files, wrong configurations, incorrect api versions and more. Leaving this on hold, so, as it's going to be a recurrent issue during the alpha.

I see you have started gathering samples, @xan105. While I consider that it is interesting to keep as much as possible, test should include only specific cases (as per platform/source): 

* Sample without achievements.
* Sample with at least one achievement.
* Sample with at least one achievement in progress.
* Sample with at least one achievement completed.
* Samples that present specific errors.

Generally, it may be also interesting to add specific situations like one `appId` with different sources, `appId` collisions between platforms and other specific multi-plugin collisions. 

I am currently using this file as a list of the samples used for testing. Some samples missing are noted, but there a lot of them that are still not in the file. I also would prefer you (or anyone willing to help) to share me the samples more than adding them directly, as they are not useful if do not have any test associated.

This is the link to the README mentioned: https://github.com/achievement-watcher/celes/tree/alpha/tests/samples

**Comment by msolefonte** [comment]
A lot of tests have been added in #39. The main problem right now is testing stuff that does not depends on samples: Steam (Steam needs to be installed) and GreenLumaEmu (Registry). Some bugs have also been found with Istanbul (the coverage tool we use).

**Comment by msolefonte** [comment]
More tests added with #40.

**Comment by msolefonte** [comment]
100% coverage achieved with #40. Closed.
